version: "3.9"
services:
  backend:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend/app/database.db:/app/backend/app/database.db

